---
title: "BEATCF enrolment tables"
author: "Edward Pan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    latex_engine: xelatex
mainfont: Arial

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo       = FALSE,
  message    = FALSE,
  warning    = FALSE
)

# Used to connect to MySQL database
library(DBI) 
library(RMySQL)

# Connect to the sql database
conn <- dbConnect( drv = RMySQL::MySQL(), dbname = "beatcf_test", host = "127.0.0.1", username = "root", password = "password123")

# test <- dbGetQuery(conn, "SELECT * FROM subject LIMIT 1;") # Run queries example
# dbDisconnect(conn) # Disconnect from the server

library(reticulate) # Library used for incorporating python chunks of code
library(stringr)
library(tidyverse)
library(gtsummary)
library(gt)
library(ggplot2)

library(kableExtra)
library(tinytex)
library(officedown)

library(latex2exp)
# library(kableExtra)
# library(flextable)
# #library(knitr)
# #library(gt)
# library(dplyr)
# library(gridExtra)
# library(expss)
# library(officedown)
# library(broom)
```

```{r}
cutoff_date <- "2023-07-01" #The Date which enrolments should be before

# Get data from MySQL Database
sql_string <- str_glue('SELECT *
FROM beatcf_enrolment_paper
WHERE enrolment_date < "{cutoff_date}" and study_id not in ("010-0004", "010-0032")') # Remove the two duplicate participants

baseline_data <- dbGetQuery(conn, sql_string)
```

```{r}
table_demographics <- baseline_data %>% 
    select(stratum, age_int, age_category, height, weight, BMI, sex, genotype, sweat_chlorine_level, pancreatic_insufficiency, cf_diab, ppfev_365, ppfev_180)%>%
    # Order the categorical variables
    mutate(sweat_chlorine_level = case_when(sweat_chlorine_level == "<40" ~ "<40",
                                            sweat_chlorine_level == "40-<60" ~ "40-<60",
                                            sweat_chlorine_level == ">=60" ~ "≥60",
                                            sweat_chlorine_level == "CFTR modulator" ~ "Concurrent CFTR modulators",
                                            sweat_chlorine_level == "Enrolment before Aug2022" ~ "Enrolment before Aug2022")) %>%
    mutate(sweat_chlorine_level = factor(sweat_chlorine_level, levels = c("<40", "40-<60", "≥60", "Concurrent CFTR modulators", "Enrolment before Aug2022"))) %>%
    mutate(age_category = case_when(age_category == ">=40y" ~ "≥40y",
                                    age_category == "<6y" ~ "<6y",
                                    age_category == "6y-<12y" ~ "6y-<12y",
                                    age_category == "12y-<18y" ~ "12y-<18y",
                                    age_category == "18y-<30y" ~ "18y-<30y",
                                    age_category == "30y-<40y" ~ "30y-<40y")) %>%
    mutate(age_category = factor(age_category, levels = c("<6y", "6y-<12y", "12y-<18y", "18y-<30y", "30y-<40y", "≥40y"))) %>%
    mutate(genotype = factor(genotype, levels = c("Homozygous F508del", "Heterozygous F508del", "Other"))) %>%
    tbl_summary(
    digits = list(all_categorical() ~ c(0, 1)),
    by = stratum,
    type = list(age_int ~ "continuous2"), # Arrange some of the variables as median / IQR
    label=list(age_int~"Median age in years (IQR)", age_category~"Age Groups", height~"Mean height in cm (SD)", weight~"Mean weight in kilograms (SD)", BMI~"BMI kg/m² (SD)", sex~"Sex", genotype~"Genotype", sweat_chlorine_level~"Sweat Chlorine Level in mmol/L", pancreatic_insufficiency~"Pancreatic Insufficiency", cf_diab~"CF diabetes mellitus", ppfev_365~"Highest ppFEV in previous 12 months", ppfev_180~"Highest ppFEV in the previous 6 months"),
    statistic = list(all_continuous() ~ "{mean} ({sd})", all_categorical() ~ "{n} ({p}%)", all_continuous2() ~ "{median} ({p25}, {p75})"),
    missing="ifany", missing_text = "(Missing)",
    percent="column") %>%
    bold_labels() %>%
    add_overall() %>%
    modify_caption("**Demographics and Clinical Baseline Characteristics**") %>%
    modify_column_hide(columns = "stat_5") %>%
    # modify_table_styling(columns = label,
    # rows = label == "Age (years)",
    # footnote = "i.e. placebo") %>%
    modify_header(stat_1 = "ppFEV1≥70\nNo Pseudomonas\nN={n}",
                  stat_2 = "ppFEV1≥70\nPseudomonas\nN={n}",
                  stat_3 = "ppFEV1<70\nNo Pseudomonas\nN={n}",
                  stat_4 = "ppFEV1<70\nPseudomonas\nN={n}")

# BMI~"BMI (kg/m^2)"

as_kable_extra(table_demographics, booktabs = TRUE, escape = FALSE, linesep = "") %>%
kable_styling(latex_options = "scale_down") %>%
column_spec(2:6, width = "2.1cm")
```

```{r} 
# CFQR ages 12 and 13
cutoff_date <- "2023-07-01" #The Date which enrolments should be before

# Get data from MySQL Database
sql_string <- str_glue('SELECT *
FROM CFQR_1213
WHERE enrolment_date < "{cutoff_date}" and study_id not in ("010-0004", "010-0032")')

cfqr1213_data <- dbGetQuery(conn, sql_string)

table_cfqr <- cfqr1213_data %>% 
    select(stratum, physical, emotional, social, body, eat, treatmentburden, respiration, digestion)%>%
    tbl_summary(
    digits = list(all_categorical() ~ c(0, 1)),
    by = stratum,
    type = list(body ~ "continuous", eat ~ "continuous", treatmentburden ~ "continuous", respiration ~ "continuous", digestion ~ "continuous"),
    label = list(physical ~ "Physical", emotional ~ "Emotional", social ~ "Social", body ~ "Body", eat ~ "Eat", treatmentburden ~ "Treatment burden", respiration ~ "Respiration", digestion ~ "Digestion"),
    statistic = list(all_continuous() ~ "{mean} ({sd})", all_categorical() ~ "{n} ({p}%)"),
    missing = "no",
    percent = "column") %>%
    bold_labels() %>%
    add_overall() %>%
    modify_column_hide(columns = "stat_5") %>%
    modify_caption("**CFQR Ages 12 and 13 at Enrolment (60 days)**") %>%
    modify_header(stat_1 = "ppFEV1≥70\nNo Pseudomonas\nN={n}",
                  stat_2 = "ppFEV1≥70\nPseudomonas\nN={n}",
                  stat_3 = "ppFEV1<70\nNo Pseudomonas\nN={n}",
                  stat_4 = "ppFEV1<70\nPseudomonas\nN={n}")

as_kable_extra(table_cfqr, booktabs = TRUE, linesep = "") %>%
kable_styling(latex_options = "scale_down") %>%
column_spec(2:6, width = "2.1cm")
```

```{r} 
# CFQR ages adolescents and adults
cutoff_date <- "2023-07-01" #The Date which enrolments should be before

# Get data from MySQL Database
sql_string <- str_glue('SELECT *
FROM CFQR_adol
WHERE enrolment_date < "{cutoff_date}" and study_id not in ("010-0004", "010-0032")')

cfqradol_data <- dbGetQuery(conn, sql_string)

table_cfqr <- cfqradol_data %>% 
    select(stratum, physical, role, vitality, emotional, social, body, eat, treatmentburden, healthperceptions, weight, respiration, digestion)%>%
    tbl_summary(
    digits = list(all_categorical() ~ c(0, 1)),
    by = stratum,
    type = list(body ~ "continuous", eat ~ "continuous", treatmentburden ~ "continuous", respiration ~ "continuous", digestion ~ "continuous", weight ~ "continuous"),
    label = list(physical ~ "Physical", role ~ "Role", vitality ~ "Vitality", emotional ~ "Emotional", social ~ "Social", body ~ "Body", eat ~ "Eat", treatmentburden ~ "Treatment burden", healthperceptions ~ "Health perceptions", weight ~ "Weight", respiration ~ "Respiration", digestion ~ "Digestion"),
    statistic = list(all_continuous() ~ "{mean} ({sd})", all_categorical() ~ "{n} ({p}%)"),
    missing = "no",
    percent = "column") %>%
    bold_labels() %>%
    add_overall() %>%
    modify_column_hide(columns = "stat_5") %>%
    modify_caption("**CFQR Adolescents and Adults at Enrolment (60 days)**") %>%
    modify_header(stat_1 = "ppFEV1≥70\nNo Pseudomonas\nN={n}",
                  stat_2 = "ppFEV1≥70\nPseudomonas\nN={n}",
                  stat_3 = "ppFEV1<70\nNo Pseudomonas\nN={n}",
                  stat_4 = "ppFEV1<70\nPseudomonas\nN={n}")

as_kable_extra(table_cfqr, booktabs = TRUE, linesep = "") %>%
kable_styling(latex_options = "scale_down") %>%
column_spec(2:6, width = "2.1cm")
```

```{r} 
# CFQR ages parents and caregivers
cutoff_date <- "2023-07-01" #The Date which enrolments should be before

# Get data from MySQL Database
sql_string <- str_glue('SELECT *
FROM CFQR_parent
WHERE enrolment_date < "{cutoff_date}" and study_id not in ("010-0004", "010-0032")')

cfqrparent_data <- dbGetQuery(conn, sql_string)

table_cfqr <- cfqrparent_data %>% 
    select(stratum, physical, emotional, school, body, eat, treatmentburden, healthperceptions, weight, respiration, digestion)%>%
    tbl_summary(
    digits = list(all_categorical() ~ c(0, 1)),
    by = stratum,
    type = list(body ~ "continuous", eat ~ "continuous", treatmentburden ~ "continuous", respiration ~ "continuous", digestion ~ "continuous", healthperceptions ~ "continuous", weight ~ "continuous"),
    label = list(physical ~ "Physical", emotional ~ "Emotional", school ~ "School", body ~ "Body", eat ~ "Eat", treatmentburden ~ "Treatment burden", healthperceptions ~ "Health perceptions", weight ~ "Weight", respiration ~ "Respiration", digestion ~ "Digestion"),
    statistic = list(all_continuous() ~ "{mean} ({sd})", all_categorical() ~ "{n} ({p}%)"),
    missing = "no",
    percent = "column") %>%
    bold_labels() %>%
    add_overall() %>%
    modify_column_hide(columns = "stat_5") %>%
    modify_caption("**CFQR Parents and Caregivers at Enrolment (60 days)**") %>%
    modify_header(stat_1 = "ppFEV1≥70\nNo Pseudomonas\nN={n}",
                  stat_2 = "ppFEV1≥70\nPseudomonas\nN={n}",
                  stat_3 = "ppFEV1<70\nNo Pseudomonas\nN={n}",
                  stat_4 = "ppFEV1<70\nPseudomonas\nN={n}")

as_kable_extra(table_cfqr, booktabs = TRUE, linesep = "") %>%
kable_styling(latex_options = "scale_down") %>%
column_spec(2:6, width = "2.1cm")
```


```{r}
cutoff_date <- "2023-07-01" #The Date which enrolments should be before

# Get data from MySQL Database
sql_string <- str_glue('SELECT *
FROM conmeds_paper_grouped
WHERE enrolment_date < "{cutoff_date}" and study_id not in ("010-0004", "010-0032")')

conmeds_data <- dbGetQuery(conn, sql_string)
```


```{r}

# Create the Footnote regarding Intravenous Antibiotic cases

footnote_string <- "Out of the antibiotics listed above there were"

sql_string <- str_glue('select * from conmeds_paper_grouped_route where Antibiotic___Azithromycin_3 = 1')
anti_data <- dbGetQuery(conn, sql_string)

if (nrow(anti_data) != 0) {
  footnote_string = paste(footnote_string, str_glue("{nrow(anti_data)} Azithromycin,"))
}

sql_string <- str_glue('select * from conmeds_paper_grouped_route where Antibiotic___Tobramycin_3 = 1')
anti_data <- dbGetQuery(conn, sql_string)

if (nrow(anti_data) != 0) {
  footnote_string = paste(footnote_string, str_glue("{nrow(anti_data)} Tobramycin,"))
}

sql_string <- str_glue('select * from conmeds_paper_grouped_route where Antibiotic___Amoxicillin_3 = 1')
anti_data <- dbGetQuery(conn, sql_string)

if (nrow(anti_data) != 0) {
  footnote_string = paste(footnote_string, str_glue("{nrow(anti_data)} Amoxicillin,"))
}

sql_string <- str_glue('select * from conmeds_paper_grouped_route where Antibiotic___Flucloxacillin_3 = 1')
anti_data <- dbGetQuery(conn, sql_string)

if (nrow(anti_data) != 0) {
  footnote_string = paste(footnote_string, str_glue("{nrow(anti_data)} Flucloxacillin,"))
}

sql_string <- str_glue('select * from conmeds_paper_grouped_route where Antibiotic___Cotrimoxazole__3 = 1')
anti_data <- dbGetQuery(conn, sql_string)

if (nrow(anti_data) != 0) {
  footnote_string = paste(footnote_string, str_glue("{nrow(anti_data)} Cotrimoxazole,"))
}

sql_string <- str_glue('select * from conmeds_paper_grouped_route where Antibiotic___Ciprofloxacin_3 = 1')
anti_data <- dbGetQuery(conn, sql_string)

if (nrow(anti_data) != 0) {
  footnote_string = paste(footnote_string, str_glue("{nrow(anti_data)} Ciprofloxacin,"))
}

footnote_string = substr(footnote_string, 1, nchar(footnote_string)-1)

footnote_string = paste(footnote_string, "intravenous cases.")

table_conmeds <- conmeds_data %>% 
    select(
  stratum, 
  Antibiotic___Azithromycin, 
  Antibiotic___Tobramycin, 
  Antibiotic___Amoxicillin, 
  Antibiotic___Flucloxacillin, 
  Antibiotic___Cotrimoxazole_, 
  Antibiotic___Ciprofloxacin, 
  Antibiotic___other,
  Antifungal,
  Corticosteroids___Inhaled,
  Corticosteroids___Nasal,
  Corticosteroids___Systemic,
  Corticosteroids___Topical,
  Dornase_Alfa, 
  Hypertonic_saline, 
  Mannitol__Bronchitol_,
  Elexacaftor_tezacaftor_ivacaftor__Trikafta_, 
  Lumacaftor_ivacaftor__Orkambi_, 
  Tezacaftor_ivacaftor_and_ivacaftor__symdeko_, 
  Ivacaftor__Kalydeco_,
  Antidepressant, 
  Antipsychotic, 
  ADHD_medication,
  Vitamin_mineral_supplements, 
  Pancreatic_enzyme_replacement, 
  Sodium_chloride__salt_, 
  Salbutamol__Ventolin_, 
  Proton_pump_inhibitor, 
  Insulin_medication, 
  Ursodeoxycholic_acid, 
  Iron_supplement
  )%>%
    tbl_summary(
    digits = list(all_categorical() ~ c(0, 1)),
    by = stratum,
    statistic = list(all_continuous() ~ "{mean} ({sd})", all_categorical() ~ "{n} ({p}%)"),
    label=list(
      Antibiotic___Amoxicillin ~ "Amoxicillin", 
      Antibiotic___Azithromycin ~ "Azithromycin", 
      Antibiotic___Ciprofloxacin ~ "Ciprofloxacin", 
      Antibiotic___Cotrimoxazole_ ~ "Cotrimoxazole", 
      Antibiotic___Flucloxacillin ~ "Flucloxacillin", 
      Antibiotic___Tobramycin ~ "Tobramycin", 
      Antibiotic___other ~ "Other",
      Corticosteroids___Inhaled ~ "Inhaled", 
      Corticosteroids___Nasal ~ "Nasal", 
      Corticosteroids___Systemic ~ "Systemic",
      Corticosteroids___Topical ~ "Topical",
      Elexacaftor_tezacaftor_ivacaftor__Trikafta_ ~ "Elexacaftor/tezacaftor/ivacaftor (Trikafta)", 
      Tezacaftor_ivacaftor_and_ivacaftor__symdeko_ ~ "Tezacaftor/ivacaftor (symdeko)", 
      Ivacaftor__Kalydeco_ ~ "Ivacaftor (Kalydeco)",
      Lumacaftor_ivacaftor__Orkambi_ ~ "Lumacaftor/ivacaftor (Orkambi)",
      Antidepressant ~ "Antidepressant", 
      Antipsychotic ~ "Antipsychotic", 
      ADHD_medication ~ "ADHD medication",
      Dornase_Alfa ~ "Dornase Alfa", 
      Mannitol__Bronchitol_ ~ "Mannitol Bronchitol", 
      Hypertonic_saline ~ "Hypertonic saline",
      Vitamin_mineral_supplements ~ "Vitamin/mineral supplements", 
      Pancreatic_enzyme_replacement ~ "Pancreatic enzyme replacement", 
      Sodium_chloride__salt_ ~ "Sodium chloride",
      Proton_pump_inhibitor ~ "Proton pump inhibitor",
      Ursodeoxycholic_acid ~ "Ursodeoxycholic acid",
      Iron_supplement ~ "Iron supplement",
      Insulin_medication ~ "Insulin medication",
      Salbutamol__Ventolin_ ~ "Bronchodilator (Salbutamol)"
      ),
    missing="no",
    percent="column",
    ) %>%
    #bold_labels() %>%
    add_overall() %>%
    modify_table_body(
      ~.x %>%
        
      # Create a dummy row for the grouping. Check which variables are needed from the table_body in the tbl_summary information
      rbind(
        tibble(
          variable="Antibiotics",
          var_type=NA,
          var_label = "Antibiotics",
          row_type="label",
          label="Antibiotics",
          stat_0= NA,
          stat_1= NA,
          stat_2= NA,
          stat_3= NA,
          stat_4= NA,
          stat_5= NA))%>% # expand the components of the tibble as needed if you have more columns
        
      rbind(
        tibble(
          variable="Corticosteroids",
          var_type=NA,
          var_label = "Corticosteroids",
          row_type="label",
          label="Corticosteroids",
          stat_0= NA,
          stat_1= NA,
          stat_2= NA,
          stat_3= NA,
          stat_4= NA,
          stat_5= NA))%>% # expand the components of the tibble as needed if you have more columns
        
      rbind(
        tibble(
          variable="Muco-active agents",
          var_type=NA,
          var_label = "Muco-active agents",
          row_type="label",
          label="Muco-active agents",
          stat_0= NA,
          stat_1= NA,
          stat_2= NA,
          stat_3= NA,
          stat_4= NA,
          stat_5= NA))%>% # expand the components of the tibble as needed if you have more columns
        
      rbind(
        tibble(
          variable="CFTR modulators",
          var_type=NA,
          var_label = "CFTR modulators",
          row_type="label",
          label="CFTR modulators",
          stat_0= NA,
          stat_1= NA,
          stat_2= NA,
          stat_3= NA,
          stat_4= NA,
          stat_5= NA))%>% # expand the components of the tibble as needed if you have more columns
        
      rbind(
        tibble(
          variable="Antidepressants/Antipsychotic",
          var_type=NA,
          var_label = "Antidepressants/Antipsychotic",
          row_type="label",
          label="Antidepressants/Antipsychotic",
          stat_0= NA,
          stat_1= NA,
          stat_2= NA,
          stat_3= NA,
          stat_4= NA,
          stat_5= NA))%>% # expand the components of the tibble as needed if you have more columns
        
        arrange(factor(variable, levels=c(
          "Antibiotics",
          "Antibiotic___Azithromycin",
          "Antibiotic___Tobramycin", 
          "Antibiotic___Amoxicillin", 
          "Antibiotic___Flucloxacillin", 
          "Antibiotic___Cotrimoxazole_", 
          "Antibiotic___Ciprofloxacin", 
          "Antibiotic___other",
          "Antifungal",
          "Corticosteroids",
          "Corticosteroids___Inhaled",
          "Corticosteroids___Nasal",
          "Corticosteroids___Systemic",
          "Corticosteroids___Topical",
          "Muco-active agents",
          "Dornase_Alfa", 
          "Hypertonic_saline", 
          "Mannitol__Bronchitol_",
          "CFTR modulators",
          "Elexacaftor_tezacaftor_ivacaftor__Trikafta_", 
          "Lumacaftor_ivacaftor__Orkambi_", 
          "Tezacaftor_ivacaftor_and_ivacaftor__symdeko_", 
          "Ivacaftor__Kalydeco_",
          "Antidepressants/Antipsychotic",
          "Antidepressant", 
          "Antipsychotic", 
          "ADHD_medication",
          "Vitamin_mineral_supplements", 
          "Pancreatic_enzyme_replacement", 
          "Sodium_chloride__salt_", 
          "Salbutamol__Ventolin_", 
          "Proton_pump_inhibitor", 
          "Insulin_medication", 
          "Ursodeoxycholic_acid", 
          "Iron_supplement"
          ))))%>%
  
    # Indent the Grouped Medications
    modify_column_indent(columns=label, rows=variable%in%c(
      "Antibiotic___Azithromycin",
      "Antibiotic___Tobramycin", 
      "Antibiotic___Amoxicillin", 
      "Antibiotic___Flucloxacillin", 
      "Antibiotic___Cotrimoxazole_", 
      "Antibiotic___Ciprofloxacin", 
      "Antibiotic___other",
      "Corticosteroids___Inhaled",
      "Corticosteroids___Nasal",
      "Corticosteroids___Systemic",
      "Corticosteroids___Topical",
      "Dornase_Alfa", 
      "Hypertonic_saline", 
      "Mannitol__Bronchitol_",
      "Elexacaftor_tezacaftor_ivacaftor__Trikafta_", 
      "Lumacaftor_ivacaftor__Orkambi_", 
      "Tezacaftor_ivacaftor_and_ivacaftor__symdeko_", 
      "Ivacaftor__Kalydeco_",
      "Antidepressant", 
      "Antipsychotic", 
      "ADHD_medication"
      ))%>%
  
    modify_table_styling(
      columns=label, rows=variable%in%c(
        "Antibiotics",
        "Antifungal",
        "Corticosteroids",
        "CFTR modulators",
        "Antidepressants/Antipsychotic",
        "Muco-active agents",
        "Vitamin_mineral_supplements", 
        "Pancreatic_enzyme_replacement", 
        "Sodium_chloride__salt_", 
        "Salbutamol__Ventolin_", 
        "Proton_pump_inhibitor", 
        "Insulin_medication", 
        "Ursodeoxycholic_acid", 
        "Iron_supplement"),
      text_format = "bold") %>%
      
    modify_caption("**Concomitant medications at enrolment**") %>%
    modify_column_hide(columns = "stat_5") %>% # Removes Other Column
    modify_table_styling(
    columns = label,
    rows = variable%in%c("Antibiotics"),
    footnote = footnote_string) %>%
    modify_header(label = "Medication Name",
                  stat_0 = "Overall\nN={n}",
                  stat_1 = "ppFEV1≥70\nNo Pseudomonas\nN={n}",
                  stat_2 = "ppFEV1≥70\nPseudomonas\nN={n}",
                  stat_3 = "ppFEV1<70\nNo Pseudomonas\nN={n}",
                  stat_4 = "ppFEV1<70\nPseudomonas\nN={n}")
    
as_kable_extra(table_conmeds, booktabs = TRUE, linesep = "") %>%
kable_styling(latex_options = "scale_down") %>%
column_spec(2:6, width = "2cm")
```

``` {r}
# Microbiology Virus
cutoff_date <- "2023-07-01" #The Date which enrolments should be before

# Get data from MySQL Database
sql_string <- str_glue('SELECT t1.*, t2.Aspergillus, t2.Candida_species, t2.Fungi_mould_yeast_Other, t3.Adenovirus, t3.COVID_19, t3.Enterovirus, t3.Influenza_, t3.PIV, t3.Rhinovirus, t3.RSV, t3.Virus_other
FROM microbiology_bacteria_final t1
INNER JOIN microbiology_fungi_final t2
INNER JOIN microbiology_virus_final t3 ON t1.study_id = t2.study_id and t1.study_id = t3.study_id
WHERE t1.enrolment_date < "{cutoff_date}" and t1.study_id not in ("010-0004", "010-0032")')

microbiology <- dbGetQuery(conn, sql_string)

# Collect the variables from the dataframe
table_microbiology <- microbiology %>%
    select(
      stratum,
      Pseudomonas_species, 
      Staphylococcus_aureus__MRSA_,
      Staphylococcus_aureus__MSSA_,
      Staphylococcus_aureus__Unknown_,
      Haemophilus_species,
      Stenotrophomonas_species,
      Mycobacterium_species,
      Pneumococcus,
      Streptococcus_pyogenes,
      Streptococcus_species,
      Escherichia_species,
      Klebsiella_species,
      Chryseobacterium_species,
      Enterobacter_species,
      Moraxella_species,
      Acinetobacterium_species,
      Achromobacter_species,
      Serratia_species,
      Burkholderia,
      Bacteria_Other,
      Rhinovirus,
      COVID_19,
      PIV,
      RSV,
      Enterovirus,
      Adenovirus,
      Influenza_,
      Virus_other,
      Aspergillus,
      Candida_species,
      Fungi_mould_yeast_Other)%>%
    tbl_summary(
      digits = list(all_categorical() ~ c(0, 1)),
      by = stratum,
      statistic = list(all_continuous() ~ "{mean} ({sd})", all_categorical() ~ "{n} ({p}%)"),
      missing="no",
      percent="column",
      label=list(
        Pseudomonas_species ~ "Pseudomonas species", 
        Staphylococcus_aureus__MRSA_ ~ "Staphylococcus species (MRSA)",
        Staphylococcus_aureus__MSSA_ ~ "Staphylococcus species (MSSA)",
        Staphylococcus_aureus__Unknown_ ~ "Staphylococcus species (Unknown)",
        Haemophilus_species ~ "Haemophilus species",
        Stenotrophomonas_species ~ "Stenotrophomonas species",
        Mycobacterium_species ~ "Mycobacterium species",
        Pneumococcus ~ "Streptococcus pneumoniae",
        Streptococcus_pyogenes ~ "Streptococcus pyogenes",
        Streptococcus_species ~ "Streptococcus species (other)",
        Escherichia_species ~ "Escherichia species",
        Klebsiella_species ~ "Klebsiella species",
        Chryseobacterium_species ~ "Chryseobacterium species",
        Enterobacter_species ~ "Enterobacter species",
        Moraxella_species ~ "Moraxella species",
        Acinetobacterium_species ~ "Acinetobacterium species",
        Achromobacter_species ~ "Achromobacter species",
        Serratia_species ~ "Serratia species",
        Burkholderia ~ "Burkholderia species", 
        Bacteria_Other ~ "Other",
        Rhinovirus ~ "Rhinovirus",
        COVID_19 ~ "SARS-CoV-2",
        PIV ~ "Parainfluenza (PIV)",
        RSV ~ "Respiratory Syncytial Virus (RSV)",
        Enterovirus ~ "Enterovirus",
        Adenovirus ~ "Adenovirus",
        Influenza_ ~ "Influenza",
        Virus_other ~ "Other",
        Aspergillus ~ "Aspergillus species",
        Candida_species ~ "Candida species",
        Fungi_mould_yeast_Other ~ "Other"
        )) %>%
    #bold_labels() %>%
    add_overall() %>%
    modify_table_body(
      ~.x %>%
        
      # Create a dummy row for the grouping. Check which variables are needed from the table_body in the tbl_summary information
      rbind(
        tibble(
          variable="Bacterial pathogen",
          var_type=NA,
          var_label = "Bacterial pathogen",
          row_type="label",
          label="Bacterial pathogen",
          stat_0= NA,
          stat_1= NA,
          stat_2= NA,
          stat_3= NA,
          stat_4= NA,
          stat_5= NA))%>% # expand the components of the tibble as needed if you have more columns
        
      rbind(
        tibble(
          variable="Viral pathogen",
          var_type=NA,
          var_label = "Viral pathogen",
          row_type="label",
          label="Viral pathogen",
          stat_0= NA,
          stat_1= NA,
          stat_2= NA,
          stat_3= NA,
          stat_4= NA,
          stat_5= NA))%>% # expand the components of the tibble as needed if you have more columns
        
      rbind(
        tibble(
          variable="Fungi",
          var_type=NA,
          var_label = "Fungi",
          row_type="label",
          label="Fungi",
          stat_0= NA,
          stat_1= NA,
          stat_2= NA,
          stat_3= NA,
          stat_4= NA,
          stat_5= NA))%>% # expand the components of the tibble as needed if you have more columns
        
        arrange(factor(variable, levels=c(
          "Bacterial pathogen",
          "Pseudomonas_species", 
          "Staphylococcus_aureus__MRSA_",
          "Staphylococcus_aureus__MSSA_",
          "Staphylococcus_aureus__Unknown_",
          "Haemophilus_species",
          "Stenotrophomonas_species",
          "Mycobacterium_species",
          "Pneumococcus",
          "Streptococcus_pyogenes",
          "Streptococcus_species",
          "Escherichia_species",
          "Klebsiella_species",
          "Enterobacter_species",
          "Chryseobacterium_species",
          "Moraxella_species",
          "Acinetobacterium_species",
          "Achromobacter_species",
          "Serratia_species",
          "Burkholderia",
          "Bacteria_Other",
          "Viral pathogen",
          "Rhinovirus",
          "COVID_19",
          "PIV",
          "RSV",
          "Enterovirus",
          "Adenovirus",
          "Influenza_",
          "Virus_other",
          "Fungi",
          "Aspergillus",
          "Candida_species",
          "Fungi_mould_yeast_Other"
          ))))%>%
  
      # Indent the Grouped Medications
    modify_column_indent(columns=label, rows=variable%in%c(
          "Pseudomonas_species", 
          "Staphylococcus_aureus__MRSA_",
          "Staphylococcus_aureus__MSSA_",
          "Staphylococcus_aureus__Unknown_",
          "Haemophilus_species",
          "Stenotrophomonas_species",
          "Mycobacterium_species",
          "Pneumococcus",
          "Streptococcus_pyogenes",
          "Streptococcus_species",
          "Escherichia_species",
          "Klebsiella_species",
          "Chryseobacterium_species",
          "Enterobacter_species",
          "Moraxella_species",
          "Acinetobacterium_species",
          "Achromobacter_species",
          "Serratia_species",
          "Burkholderia",
          "Bacteria_Other",
          "Rhinovirus",
          "COVID_19",
          "PIV",
          "RSV",
          "Enterovirus",
          "Adenovirus",
          "Influenza_",
          "Virus_other",
          "Aspergillus",
          "Candida_species",
          "Fungi_mould_yeast_Other"
      ))%>%
  
    modify_table_styling(
      columns=label, rows=variable%in%c(
        "Bacterial pathogen",
        "Viral pathogen",
        "Fungi"),
      text_format = "bold") %>%
  
    modify_column_hide(columns = "stat_5") %>%
    modify_caption("**Microbiology at enrolment**") %>%
    modify_header(label = "Microbiology",
                  stat_0 = "Overall\nN={n}",
                  stat_1 = "ppFEV1≥70\nNo Pseudomonas\nN={n}",
                  stat_2 = "ppFEV1≥70\nPseudomonas\nN={n}",
                  stat_3 = "ppFEV1<70\nNo Pseudomonas\nN={n}",
                  stat_4 = "ppFEV1<70\nPseudomonas\nN={n}")

as_kable_extra(table_microbiology, booktabs = TRUE, linesep = "") %>%
kable_styling(latex_options = "scale_down") %>%
column_spec(2:6, width = "2.1cm")
```
